# Einfache Variablen
db_username = "John"
db_password = "12345qwerty"

# Gruppierte Variablen
[grouped_variables]
things_i_like = ["Python", "Streamlit"]

[connections.demo_db]
url = "postgresql://streamlit:somePassword@postgres:5432/streamlit_web"
